apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: caller-wf
on:
  workflow_dispatch:
    inputs:
      requiredInput:
        type: number
        required: true
  
jobs:
  call_rw_1:
    uses: vinamdar-cloudbees/mask-example-repo-1/.cloudbees/workflows/reusable-wf.yaml
    with:
      requiredInput: ${{ inputs.requiredInput }}
    