name: mask-example-wf-1
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on:
  push:
    branches:
      - main
 
jobs:
  fetch-secrets-job:
    outputs:
      secret-vars: ${{ steps.fetch-secrets-step.outputs.conjur_output }}
    steps:
      - name: fetch-secrets-step
        id: fetch-secrets-step
        uses: cloudbees-io/cyberark-conjur-fetch-secrets@main
        with:
          url: ${{ vars.CONJURE_URL }}
          api-key: ${{ secrets.CONJURE_API_KEY }}
          login: 'host%2Fdata%2Fca04-dev-db'
          variables: data/DEV-DC1-ENG-DB/oracle-admin-creds/password,data/DEV-DC1-ENG-DB/oracle-admin-creds/username

      - name: use-secrets-step
        uses: docker://golang:1.20-alpine
        shell: sh
        run: | # These echo commands will mask the secrets since they are already masked in the action of the same job
          echo "Using secrets in another step"
          echo ${{ fromJSON(steps.fetch-secrets-step.outputs.secret-vars).data_DEV-DC1-ENG-DB_oracle-admin-creds_password }}
          echo ${{ fromJSON(steps.fetch-secrets-step.outputs.secret-vars).data_DEV-DC1-ENG-DB_oracle-admin-creds_username }}
          echo ${{ fromJSON(steps.fetch-secrets-step.outputs.secret-vars).data_DEV-DC1-ENG-DB_oracle-admin-creds_password }}
          echo ${{ fromJSON(steps.fetch-secrets-step.outputs.secret-vars).data_DEV-DC1-ENG-DB_oracle-admin-creds_username }}
